@extends('hr.layouts.app')

@section('title', 'Payroll Runs')
@section('heading', 'Payroll')

@section('content')
<div class="space-y-6">

    {{-- Generate new run --}}
    @if(Auth::guard('hr')->user()->canDo('generate_payroll'))
    <div class="bg-white rounded-xl border border-gray-200 p-6">
        <h2 class="text-sm font-semibold text-gray-700 mb-4">Generate Payroll Run</h2>
        <form method="POST" action="{{ route('hr.payroll.generate') }}" class="flex items-end gap-4">
            @csrf
            <div>
                <label class="block text-xs text-gray-500 mb-1">Period (YYYY-MM)</label>
                <input type="month" name="period" value="{{ now()->subMonth()->format('Y-m') }}"
                       class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand/30 focus:border-brand">
            </div>
            <button type="submit"
                    onclick="return confirm('Generate payroll for selected period?')"
                    class="bg-brand hover:bg-brand-600 text-white text-sm font-medium px-5 py-2 rounded-lg transition-colors">
                Generate Run
            </button>
        </form>
        @error('period')<p class="mt-2 text-red-500 text-xs">{{ $message }}</p>@enderror
    </div>
    @endif

    {{-- Runs list --}}
    <div class="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div class="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
            <h2 class="text-sm font-semibold text-gray-700">All Runs</h2>
            <span class="text-xs text-gray-400">{{ $runs->count() }} total</span>
        </div>

        @if($runs->isEmpty())
        <div class="py-16 text-center text-gray-400 text-sm">No payroll runs yet.</div>
        @else
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 text-xs text-gray-500 uppercase tracking-wide">
                    <tr>
                        <th class="px-6 py-3 text-left">Period</th>
                        <th class="px-6 py-3 text-left">Status</th>
                        <th class="px-6 py-3 text-right">Employees</th>
                        <th class="px-6 py-3 text-right">Gross</th>
                        <th class="px-6 py-3 text-right">Deductions</th>
                        <th class="px-6 py-3 text-right">Net</th>
                        <th class="px-6 py-3 text-left">Generated By</th>
                        <th class="px-6 py-3"></th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-50">
                    @foreach($runs as $run)
                    <tr class="hover:bg-gray-50 transition-colors">
                        <td class="px-6 py-4 font-mono font-medium text-gray-900">{{ $run->period }}</td>
                        <td class="px-6 py-4">
                            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {{ $run->status_badge_class }}">
                                {{ $run->status_label }}
                            </span>
                        </td>
                        <td class="px-6 py-4 text-right font-tabular">{{ $run->employee_count }}</td>
                        <td class="px-6 py-4 text-right font-tabular">${{ number_format($run->total_gross, 2) }}</td>
                        <td class="px-6 py-4 text-right font-tabular text-red-600">${{ number_format($run->total_deductions, 2) }}</td>
                        <td class="px-6 py-4 text-right font-tabular font-semibold">${{ number_format($run->total_net, 2) }}</td>
                        <td class="px-6 py-4 text-gray-500">{{ $run->generator?->name ?? '—' }}</td>
                        <td class="px-6 py-4 text-right">
                            <a href="{{ route('hr.payroll.show', $run) }}"
                               class="text-navy hover:text-brand font-medium text-xs">View →</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
    </div>

</div>
@endsection
