<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $templates = [
            // ── Re-engagement ─────────────────────────────────────────────────
            [
                'slug'             => 'reengagement_3d',
                'type'             => 'reengagement',
                'label'            => 'Re-engage — 3 Days Inactive',
                'title_template'   => '👋 We miss you!',
                'body_template'    => 'It\'s been 3 days! Come back and discover what\'s new on eSahlan.',
                'title_so'         => '👋 Waan kugu xiisnahnahay!',
                'body_so'          => 'Muddo 3 maalmood ah! Ku soo noqo oo eSahlan-ka wax cusub ka hel.',
                'language'         => 'en',
                'interval_hours'   => 72,
                'target_audience'  => 'inactive_3d',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'reengagement_7d',
                'type'             => 'reengagement',
                'label'            => 'Re-engage — 7 Days Inactive',
                'title_template'   => '🎁 A special offer just for you!',
                'body_template'    => '7 days without eSahlan? We have a surprise waiting for you. Come back now!',
                'title_so'         => '🎁 Hadiyad gaar ah oo adigu kuu gaar ah!',
                'body_so'          => '7 maalmood eSahlan la\'aanteed? Yaab ayaa kugu sugaya. Hadda ku soo noqo!',
                'language'         => 'en',
                'interval_hours'   => 168,
                'target_audience'  => 'inactive_7d',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'reengagement_14d',
                'type'             => 'reengagement',
                'label'            => 'Re-engage — 14 Days Inactive',
                'title_template'   => '💔 Still there?',
                'body_template'    => 'We saved your favorites! Your restaurants and shops are waiting for you on eSahlan.',
                'title_so'         => '💔 Ma weli joogtaa?',
                'body_so'          => 'Abuurtaadii ayaan kaydinnay! Mataamihaadii iyo dukaanyadaadii waxay kugu sugayaan eSahlan-ka.',
                'language'         => 'en',
                'interval_hours'   => 336,
                'target_audience'  => 'inactive_14d',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'reengagement_30d',
                'type'             => 'reengagement',
                'label'            => 'Re-engage — 30 Days Inactive',
                'title_template'   => '⚡ Last chance! Come back.',
                'body_template'    => '30 days — we\'ve added so much! New restaurants, new features. Don\'t miss out.',
                'title_so'         => '⚡ Fursadda ugu dambeysa! Ku soo noqo.',
                'body_so'          => '30 maalmood — wax badan ayaan kusoo korinnay! Mataamyo cusub, astaamaha cusub. Ha maqnaanin.',
                'language'         => 'en',
                'interval_hours'   => 720,
                'target_audience'  => 'inactive_30d',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── Time-based ────────────────────────────────────────────────────
            [
                'slug'             => 'lunch_time',
                'type'             => 'time_based',
                'label'            => 'Lunch Time Promo (11:30 AM)',
                'title_template'   => '🍽️ Lunch time!',
                'body_template'    => 'Order from your favorite restaurants now — fast delivery to your door!',
                'title_so'         => '🍽️ Waqtiga qadada!',
                'body_so'          => 'Hadda ka dalbo mataamaha aad jeceshahay — gaadhsiinta degdeg ah albaabkaaga!',
                'language'         => 'en',
                'interval_hours'   => 24,
                'target_audience'  => 'all',
                'is_active'        => false,
                'send_time'        => '11:30',
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'evening_deals',
                'type'             => 'time_based',
                'label'            => 'Evening Deals (6:00 PM)',
                'title_template'   => '🛍️ Evening deals are live!',
                'body_template'    => 'Great discounts on eShop & eGrocery. Shop before they\'re gone!',
                'title_so'         => '🛍️ Qiimaha habeennimada wuu furan yahay!',
                'body_so'          => 'Qiimo dhimis weyn oo ku jira eShop & eGrocery. Iibso ka hor intaanay dhammaan!',
                'language'         => 'en',
                'interval_hours'   => 24,
                'target_audience'  => 'all',
                'is_active'        => false,
                'send_time'        => '18:00',
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'weekend_promo',
                'type'             => 'time_based',
                'label'            => 'Weekend Special (Friday)',
                'title_template'   => '🎉 Weekend vibes!',
                'body_template'    => 'Celebrate the weekend with special deals across all eSahlan services!',
                'title_so'         => '🎉 Xasilloonida fasaxa!',
                'body_so'          => 'Fasaxa u xusi xasilloon qiimaha gaarka ah ee adeegyada eSahlan oo dhan!',
                'language'         => 'en',
                'interval_hours'   => 168,
                'target_audience'  => 'all',
                'is_active'        => false,
                'send_time'        => '10:00',
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── Vendor ────────────────────────────────────────────────────────
            [
                'slug'             => 'new_vendor_district',
                'type'             => 'vendor',
                'label'            => 'New Vendor in Your District',
                'title_template'   => '🏪 New {module} opened near you!',
                'body_template'    => '{store_name} just joined eSahlan in {district}. Check them out!',
                'title_so'         => '🏪 {module} cusub oo kuu dhow ayaa furmaay!',
                'body_so'          => '{store_name} ayaa eSahlan ku biirtay {district}. Hubi!',
                'language'         => 'en',
                'interval_hours'   => 1,
                'target_audience'  => 'new_vendor_district',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── Loyalty ───────────────────────────────────────────────────────
            [
                'slug'             => 'points_expiry',
                'type'             => 'loyalty',
                'label'            => 'Reward Points Expiring Soon',
                'title_template'   => '⏳ Your points expire soon!',
                'body_template'    => 'You have {points} reward points expiring in 3 days. Use them before they\'re gone!',
                'title_so'         => '⏳ Dhibcahaagu way dhici doonaan!',
                'body_so'          => 'Waxaad leedahay {points} dhibco abaalgud ah oo 3 maalmood gudahood dhici doona. Isticmaal ka hor intaanay dhacin!',
                'language'         => 'en',
                'interval_hours'   => 24,
                'target_audience'  => 'all',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'slug'             => 'wallet_low',
                'type'             => 'loyalty',
                'label'            => 'Low Wallet Balance Reminder',
                'title_template'   => '💳 Top up your ePay wallet!',
                'body_template'    => 'Your ePay balance is running low. Add funds for faster checkout on your next order!',
                'title_so'         => '💳 Kusoo dar lacag ePay wallet-kaaga!',
                'body_so'          => 'Hantidaada ePay way yartahay. Ku dar lacag si aad ugu hesho lacag bixin degdeg ah markad dalbasho xigta!',
                'language'         => 'en',
                'interval_hours'   => 72,
                'target_audience'  => 'all',
                'is_active'        => false,
                'send_time'        => null,
                'channel_id'       => 'esahlan_promo',
                'settings'         => null,
                'last_sent_at'     => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
        ];

        foreach ($templates as $tpl) {
            DB::table('auto_notification_templates')->updateOrInsert(
                ['slug' => $tpl['slug']],
                $tpl,
            );
        }
    }

    public function down(): void
    {
        $slugs = [
            'reengagement_3d', 'reengagement_7d', 'reengagement_14d', 'reengagement_30d',
            'lunch_time', 'evening_deals', 'weekend_promo',
            'new_vendor_district',
            'points_expiry', 'wallet_low',
        ];
        DB::table('auto_notification_templates')->whereIn('slug', $slugs)->delete();
    }
};
