@extends('admin.layouts.app')
@section('title', 'HR Payroll Oversight')

@section('content')
<div class="container-fluid">

    <div class="page-title-box d-flex align-items-center justify-content-between mb-4">
        <h4 class="mb-0">HR Payroll — Admin View</h4>
        <span class="badge bg-info">Read-only</span>
    </div>

    {{-- Runs list --}}
    <div class="card shadow-sm mb-4">
        <div class="card-header bg-white">
            <h6 class="mb-0 fw-semibold">All Payroll Runs</h6>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="table-light text-uppercase" style="font-size:.75rem;letter-spacing:.05em;">
                        <tr>
                            <th class="px-4 py-3">Period</th>
                            <th class="px-4 py-3">Status</th>
                            <th class="px-4 py-3 text-end">Employees</th>
                            <th class="px-4 py-3 text-end">Gross</th>
                            <th class="px-4 py-3 text-end">Deductions</th>
                            <th class="px-4 py-3 text-end">Net</th>
                            <th class="px-4 py-3">Generated By</th>
                            <th class="px-4 py-3">Approved By</th>
                            <th class="px-4 py-3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($runs as $run)
                        <tr>
                            <td class="px-4 py-3 fw-semibold font-monospace">{{ $run->period }}</td>
                            <td class="px-4 py-3">
                                <span class="badge {{ match($run->status) {
                                    'draft'            => 'bg-secondary',
                                    'pending_approval' => 'bg-warning text-dark',
                                    'approved'         => 'bg-success',
                                    'paid'             => 'bg-primary',
                                    default            => 'bg-light text-dark',
                                } }}">{{ $run->status_label }}</span>
                            </td>
                            <td class="px-4 py-3 text-end">{{ $run->employee_count }}</td>
                            <td class="px-4 py-3 text-end font-monospace">${{ number_format($run->total_gross, 2) }}</td>
                            <td class="px-4 py-3 text-end font-monospace text-danger">-${{ number_format($run->total_deductions, 2) }}</td>
                            <td class="px-4 py-3 text-end font-monospace fw-bold">${{ number_format($run->total_net, 2) }}</td>
                            <td class="px-4 py-3 text-muted" style="font-size:.85rem;">{{ $run->generator?->name ?? '—' }}</td>
                            <td class="px-4 py-3 text-muted" style="font-size:.85rem;">{{ $run->approver?->name ?? '—' }}</td>
                            <td class="px-4 py-3 text-end">
                                <span class="text-muted" style="font-size:.8rem;">{{ $run->payslips()->count() }} slips</span>
                                @if(Auth::user()?->role === 'super_admin' && $run->status === 'paid')
                                <button class="btn btn-xs btn-outline-warning ms-2"
                                        onclick="openUnlock({{ $run->id }}, '{{ $run->period }}')">
                                    Unlock
                                </button>
                                @endif
                            </td>
                        </tr>
                        @empty
                        <tr><td colspan="9" class="text-center py-5 text-muted">No payroll runs yet.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {{-- Approvals Timeline --}}
    @if($timeline->count())
    <div class="card shadow-sm">
        <div class="card-header bg-white">
            <h6 class="mb-0 fw-semibold">Approvals Timeline</h6>
        </div>
        <div class="card-body">
            <ol class="position-relative border-start ps-4" style="border-left:2px solid #dee2e6!important;">
                @foreach($timeline as $log)
                <li class="mb-4 ms-2">
                    <span class="position-absolute d-flex align-items-center justify-content-center"
                          style="width:10px;height:10px;background:#1B1444;border-radius:50%;left:-6px;margin-top:4px;"></span>
                    <div class="text-muted" style="font-size:.75rem;">{{ $log->created_at->format('d M Y H:i') }}</div>
                    <div class="fw-semibold" style="font-size:.9rem;">{{ $log->action }}</div>
                    @if($log->actor_name)
                    <div class="text-muted" style="font-size:.8rem;">by {{ $log->actor_name }}</div>
                    @endif
                    @if($log->extra && isset($log->extra['note']))
                    <div class="text-muted fst-italic" style="font-size:.8rem;">{{ $log->extra['note'] }}</div>
                    @endif
                </li>
                @endforeach
            </ol>
        </div>
    </div>
    @endif

</div>

@if(Auth::user()?->role === 'super_admin')
{{-- Unlock payroll modal --}}
<div class="modal fade" id="unlockModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">⚠ Unlock Paid Payroll Run</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form id="unlockForm" method="POST">
                @csrf
                <div class="modal-body">
                    <p class="text-warning-emphasis">This will revert a paid payroll run back to <strong>approved</strong> status, allowing re-marking of payslips. This action is audited.</p>
                    <p id="unlockRunLabel" class="fw-semibold"></p>
                    <div class="mb-3">
                        <label class="form-label">Reason <span class="text-danger">*</span></label>
                        <textarea name="reason" required rows="3" maxlength="500" class="form-control" placeholder="State the reason for this override…"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-warning">Confirm Unlock</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
function openUnlock(id, period) {
    document.getElementById('unlockForm').action = '/admin/hr/payroll/' + id + '/unlock';
    document.getElementById('unlockRunLabel').textContent = 'Run: ' + period;
    new bootstrap.Modal(document.getElementById('unlockModal')).show();
}
</script>
@endif
@endsection
